= Piping logs to Logstash using Rsyslog
David Welman
2019-06-01

== Prelude
The typical method for getting trailing log files into Logstash is using the ELK stack tool Filebeat. It was found that Filebeat could not be installed on z-linux hence the need for an alternative.

=== rsyslog
rsyslog is a logging utility found on most linux distributions, including z-linux, that can monitor files and directories for changes and then log those using a format called 'syslog' hence the name. The way rsyslog is being used in this situation is simple:

 - rsyslog has been configured to be notified of updates of a particular file found under "/var/log".
 - It has been configured to send said updates of that file to a particular server address over a specific port using TCP.

The following line is required to enable rsyslog to monitor external files for updates:

./etc/rsyslog.conf
[soure, config]
---------------
module(load="imfile" mode="inotify")
---------------

"inotify" is always preferable to polling and should always be used unless bugs are encountered with it.

Next, create a config file for the specific file to be monitored, this will also contain the config information necessary to send the tailed logs to the Logstash server. 

./etc/rsyslog.d/filename.conf
--------------
    input(type="imfile"
        File="/var/log/logfile_name.log"
        Tag="logfile-name-tag"
        PersistStateInterval="1000"
        ReadMode="0"
        AddMetaData="on"
        ReopenOnTruncate="on"
        TrimLineOverBytes="0"
        FreshStartTail="on"
    )
    template(name="ForwardFormat" type="list") {
        property(name="msg" spifno1stsp="on" )
        property(name="msg")
    }
    if $programname == logfile-name-tag' then {
    action(
            type="omfwd"
            Target="server address/ip"
            Port="logstash listening port"
            Protocol="tcp"
            Template="ForwardFormat"
        )
        stop
    }
--------------

Once the following config files have been updated and created, the following command can be run to ensure that the added config is valid and is free of syntax errors:
--------
    rsyslogd -N 1
--------

Once the newly added changes have been verified, rsyslog can be restarted through the following command:
-----
    sudo service rsyslog restart
-----

=== Logstash
Logstash is a part of the ELK stack that acts as log storage for Elastic Search. The following will be configuration steps to allow it to receive messages on a specific port over TCP, as well as a Grok pattern to transform incoming logs from Websphere.

In the folder that the pipelines are found for Logstash, for example "/pipeline" on a docker container, add a new config file with the following config details in it:

./pipeline/tcp-input.conf
-----
    input {
        tcp {
            port => XXXX
        }
    }
    output {
        stdout {
            codec => rubydebug
        }
    }
-----

Set the port for the TCP input to whatever port is being used as per setup, the default is '5044'.

As for output the current setup will print straight to stdout which allows for debugging to ensure everything is working, this can later be updated to pipe the logs to Elastic or configured for any other purposes.

Finally, this is the Grok pattern that can be used to configure a log from IBM Websphere:

-----
    filter {
        grok {
            match => { "message" => "\[%{DATE:date} %{TIME:time} %{WORD:timezone}\] %{BASE16NUM:address} %{WORD:component} %{WORD:loglevel} %{DATA:classname} %{WORD:request} %{GREEDYDATA:errormessage}" }
            overwrite => ["message"]
        }
    }
-----

This filter can be added to the above Logstash config file in the following format:

-----

    input {
        ...
    }
    filter {
        ...
    }
    output {
        ...
    }
-----

=== Testing

To test the whole setup, on the machine that is running the modified rsyslog the following command can be run:

-----
    echo "Test" | nc SERVER_ADDRESS LOGSTASH_PORT
-----

If all is working, the logstash instance will receive a message of "Test"